sudo: required

language: java

env:
  - MAVEN_OPTS=-Xmx2048M

services:
  - docker

before_install:
  # - setup_docker.sh
  - docker-compose rm -f
  - docker-compose pull

script: 
  - cd datavault
  - mvn clean
  - mvn package -Dmaven.test.skip=true # required for docker build
  - cd ..
  - docker-compose build
  - docker-compose up -d
  - cd datavault
  - mvn test

after_script:
  - docker-compose stop -t 1
