version: '2'
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    volumes:
      - ./rabbitmq_data:/bitnami
    environment:
      RABBITMQ_USERNAME: datavault
      RABBITMQ_PASSWORD: datavault
    networks:
      - mqnet

  mysql:
    image: mysql:5.7
    ports:
      - "53306:3306"
    # volumes:
    #   - ./db_data:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unbr34kable
      MYSQL_DATABASE: datavault
      MYSQL_USER: datavault
      MYSQL_PASSWORD: datavault
    networks:
      - dbnet

  web:
    build:
      context: .
      dockerfile: Dockerfile_datavault
    ports:
      - "58080:8080"
    volumes:
      - ./tmp/datavault/active:/tmp/datavault/active:rw
      - ./tmp/datavault/archive:/tmp/datavault/archive:rw
      - ./tmp/datavault/temp:/tmp/datavault/temp:rw
      - ./tmp/datavault/meta:/tmp/datavault/meta:rw
      - ./datavault/datavault-assembly/target/datavault-assembly-1.0-SNAPSHOT-assembly/datavault-home/lib:/docker_datavault-home/lib:rw
      - ./datavault/datavault-assembly/target/datavault-assembly-1.0-SNAPSHOT-assembly/datavault-home/webapps:/docker_datavault-home/webapps:rw
      - ./tmp/Users:/Users:rw
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq
      - mysql

  workers:
    build: 
      context: .
      dockerfile: Dockerfile_worker
    volumes:
      - ./tmp/datavault/active:/tmp/datavault/active:rw
      - ./tmp/datavault/archive:/tmp/datavault/archive:rw
      - ./tmp/datavault/temp:/tmp/datavault/temp:rw
      - ./tmp/datavault/meta:/tmp/datavault/meta:rw
      - ./datavault/datavault-assembly/target/datavault-assembly-1.0-SNAPSHOT-assembly/datavault-home/lib:/docker_datavault-home/lib:rw
      - ./tmp/Users:/Users:rw
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq
      - mysql
      - web

# volumes:
#   db_data:
#   rabbitmq_data:
 
networks:
  dbnet:
    driver: bridge
  mqnet:
    driver: bridge