version: '2.1'
services:
  rabbitmq:
    container_name: datavault-dev-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: datavault
      RABBITMQ_DEFAULT_PASS: datavault
    networks:
      - mqnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    container_name: datavault-dev-mysql
    image: mysql:5.7
    ports:
      - "53306:3306"
    volumes:
      - ./db_data:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unbr34kable
      MYSQL_DATABASE: datavault
      MYSQL_USER: datavault
      MYSQL_PASSWORD: datavault
    networks:
      - dbnet

  web:
    container_name: datavault-dev-web
    build:
      context: .
      dockerfile: Dockerfile_datavault
    ports:
      - "58080:8080"
    volumes:
      - ./tmp/datavault/active:/tmp/datavault/active:rw
      - ./tmp/datavault/archive:/tmp/datavault/archive:rw
      - ./tmp/datavault/temp:/tmp/datavault/temp:rw
      - ./tmp/datavault/meta:/tmp/datavault/meta:rw
      - ../datavault/datavault-assembly/target/datavault-assembly-1.0-SNAPSHOT-assembly/datavault-home/lib:/docker_datavault-home/lib
      - ../datavault/datavault-assembly/target/datavault-assembly-1.0-SNAPSHOT-assembly/datavault-home/webapps:/docker_datavault-home/webapps
      - ./tmp/Users:/Users:rw
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq
      - mysql

  worker:
    container_name: datavault-dev-worker
    build:
      context: .
      dockerfile: Dockerfile_worker
    volumes:
      - ./tmp/datavault/active:/tmp/datavault/active:rw
      - ./tmp/datavault/archive:/tmp/datavault/archive:rw
      - ./tmp/datavault/temp:/tmp/datavault/temp:rw
      - ./tmp/datavault/meta:/tmp/datavault/meta:rw
      - ../datavault/datavault-worker/target:/docker_datavault-home/lib:rw
      - ./tmp/Users:/Users:rw
    networks:
      - mqnet
    depends_on:
      - rabbitmq

# volumes:
#   db_data:
#   rabbitmq_data:

networks:
  dbnet:
    driver: bridge
  mqnet:
    driver: bridge
