
SET FOREIGN_KEY_CHECKS = 0; 
TRUNCATE TABLE Events; 
TRUNCATE TABLE Jobs;  
TRUNCATE TABLE DepositChunks; 
TRUNCATE TABLE DepositPaths;
TRUNCATE TABLE Retrieves;
TRUNCATE TABLE Deposits;
SET FOREIGN_KEY_CHECKS = 1;
